ignore:
  - "tests/*"
  - "*.md"
  - "*.yml"
  - "*.yaml"
  - "*.json"
  - "*.toml"
  - "*.log"
  - "*.txt"
  - "*.html"
  - "**/setup.py"
  - "moldga/dga_main.py"
  - "moldga/plotting.py"
  - "moldga/config_parser.py"
  - "moldga/symmetrize_new.py"
